### ISSUE TITLE
Cannot write a binary parameter type

### ISSUE THREAD

**Issue by merose** [yamcs/python-yamcs-client#10]
When trying to set a BinaryParameterType parameter using a `bytes` object, the type is not supported in the Python client.

```
>>> processor.set_parameter_value('/ViperGround/Images/StereoCamera_right_jpeg', value)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/merose/.virtualenvs/viper/lib/python3.7/site-packages/yamcs/tmtc/client.py", line 519, in set_parameter_value
    req = _build_value_proto(value)
  File "/Users/merose/.virtualenvs/viper/lib/python3.7/site-packages/yamcs/tmtc/client.py", line 126, in _build_value_proto
    raise YamcsError("Unrecognized type")
yamcs.core.exceptions.YamcsError: Unrecognized type
```

It should be possible to set both binary and array parameter types.

In client.py lines 111-130, there is code to construct the protobuf value for setting a parameter using `processor.set_parameter_value`. It appears not to support binary or array parameter types.

```
def _build_value_proto(value):
    proto = yamcs_pb2.Value()
    if isinstance(value, bool):
        proto.type = proto.BOOLEAN
        proto.booleanValue = value
    elif isinstance(value, float):
        proto.type = proto.FLOAT
        proto.floatValue = value
    elif isinstance(value, int) and value > 2147483647:
        proto.type = proto.SINT64
        proto.sint64Value = value
    elif isinstance(value, int):
        proto.type = proto.SINT32
        proto.sint32Value = value
    elif isinstance(value, str):
        proto.type = proto.STRING
        proto.stringValue = value
    else:
        raise YamcsError("Unrecognized type")
    return proto
```

**Comment by fqqb** [comment]
on master
